name: Run Tests

on:
  push:  # Trigger on push requests 
    branches:
      - main  
  pull_request:  # Trigger on pull requests 
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest # latest version of ubuntu runner by github

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'
   - name: Install Yarn # install yarn first
      run: npm install -g yarn
    - name: Install dependencies
      run: yarn

    - name: Run tests
      run: yarn test
